Prepare release v0.1.0
edgehog-device-manager/edgehog-device-forwarder-proto pull request #10
Opened 2024-05-29 16:10 UTC by rgallor

2024-05-29 16:12 UTC, harlem88 commented
Change to release-0.1 branch

2024-05-29 16:16 UTC, harlem88 approved these changes

2024-05-29 16:18 UTC, noaccOS commented on .reuse/dep5
> +License: Apache-2.0
I'd rather have a `CHANGELOG.md.license` instead of a dep5 entry

2024-05-29 16:21 UTC, noaccOS commented on .reuse/dep5
> +License: Apache-2.0
Also our markdown files are usually licensed under some creative commons instead of Apache

2024-05-30 10:45 UTC, noaccOS requested changes

2024-05-30 10:45 UTC, noaccOS commented on elixir/edgehog_device_forwarder_proto/mix.exs
> +      version: "0.1.0",
please do this in a separate commit

2024-05-30 10:45 UTC, noaccOS commented on CHANGELOG.md.license
> +SPDX-License-Identifier: Apache-2.0
Our markdown files are usually licensed under some creative commons instead of Apache

2024-05-30 10:53 UTC, rgallor commented on elixir/edgehog_device_forwarder_proto/mix.exs
> +      version: "0.1.0",
ok

2024-05-31 15:52 UTC, rbino approved these changes

2024-06-03 08:47 UTC, harlem88 approved these changes

2024-06-03 12:29 UTC, joshuachp approved these changes

2024-06-03 13:39 UTC, merged